### ISSUE TITLE
Suggestion: Select Field Values

### ISSUE THREAD

**Issue by seebach** [stefanwalther/sense-range-slider#3]
Hi Stefan,

I expect that I soon will need this extension. But I will need it to select values in a field, rather than setting variables. Is this something you have in your roadmap?

One might also argue, that this would be better as a separate extension. So we don't need to set up options to select variables or fields. Whats your thoughts on this?

**Comment by stefanwalther** [comment]
Hi, yes, definitely something I'd like to consider, but before that I am planning a completely re-write of this extensions to make the overall experience better.

**Comment by stefanwalther** [comment]
Forgot to answer one of your question: No, I think it should be in the same extension.

**Comment by stefanwalther** [comment]
Closing, since working on a new slider extensions.
