### ISSUE TITLE
overlapping labels

### ISSUE THREAD

**Issue by laujerry** [stefanwalther/sense-range-slider#7]
Hi Stefan

i am trying to use this extension now
it is very nice but just sometimes the min and max labels will overlap each other at unknown condition
is this a known issue and will it be fixed in the future?
i am using qlik sense desktop 2.1.1

![image](https://cloud.githubusercontent.com/assets/18694730/14843881/3592dd80-0c86-11e6-8936-58ade8ccc688.png)

Thanks and regards,
Jerry

**Comment by ahelaatabi** [comment]
Hi, Thanks for sharing your extension very useful. Right now, I'm facing the same issue as Jerry above here but using differently on a server edition. 

Thanks,
Hakim

**Comment by stefanwalther** [comment]
Thx for reporting. I am unfortunately in the process of a major rewrite of this extension, need to get this done first and hope that this behavior is then also solved completely.
