### ISSUE TITLE
Labelling

### ISSUE THREAD

**Issue by j-hin** [stefanwalther/sense-range-slider#8]
Hi Stefan, 

Thank you for the extension! It's helped so much. 

I'm wondering if it would be possible to add the functionality of labelling each step in the slider, so we will know what exactly we are selecting please. 

Thanks, 
J

**Comment by stefanwalther** [comment]
Hi, I am working for a while on a much better slider. Hope, that I can publish that soon. That new slider will also have the option you have described. So I won't fix it in this repo (since I will deprecate it); stay tuned.
